<a href="https://colab.research.google.com/github/ankitashrivastav12/ML-MODEL/blob/main/multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
pip install word2number

In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import math
from word2number import w2n

In [29]:
df=pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [19]:
med_bed=math.floor(df.bedrooms.median())
med_bed

4

In [20]:
df.bedrooms=df.bedrooms.fillna(med_bed)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [21]:
ref=linear_model.LinearRegression()
ref.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [22]:
ref.predict([[3800,2,29]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([600218.22205104])

In [69]:
df1=pd.read_csv("hiring.csv")
df1

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [70]:
df1.experience=df1.experience.fillna("zero")
df1

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [71]:
med_score=math.floor(df1.test_score.mean())
df1.test_score=df1.test_score.fillna(med_score)
df1

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         7.0                7   72000
7     eleven         7.0                8   80000

In [72]:
df1.experience = df1.experience.astype(str)
df1.experience = df1.experience.apply(w2n.word_to_num)
df1

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000

In [73]:
ref=linear_model.LinearRegression()
ref.fit(df1[["experience","test_score","interview_score"]],df1.salary)

LinearRegression()

In [75]:
ref.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [76]:
ref.intercept_

14992.65144669314

In [79]:
ref.predict([[2,9,6]])


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [80]:
2922.26901502*2+2221.30909959*9+2147.48256637*6+14992.65144669314

53713.86677126314

In [81]:
ref.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])